version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: faitness-db
    environment:
      POSTGRES_DB: faitness
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: faitness-api
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: faitness
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: faitness-web
    ports:
      - "80:80"
    depends_on:
      - backend

  mcp-server:
    build: ./ai/mcp-server
    container_name: faitness-mcp-server
    environment:
      API_BASE_URL: http://backend:3001
      PORT: 3002
      NODE_ENV: production
    ports:
      - "3002:3002"
    depends_on:
      - backend
    volumes:
      - ./ai/mcp-server:/app
      - /app/node_modules

volumes:
  postgres_data:
