version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: faitness-db-dev
    environment:
      POSTGRES_DB: faitness
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: faitness-api-dev
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: faitness
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: faitness-web-dev
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mcp-server:
    build:
      context: ./ai/mcp-server
      dockerfile: Dockerfile.dev
    container_name: faitness-mcp-dev
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
    volumes:
      - ./ai/mcp-server:/app
      - /app/node_modules
      - /app/dist
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev: